version: '3.8'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=123456789
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql
    networks:
      - app-network

  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
      - ./model:/app/model
    ports:
      - "5000:5000"
    depends_on:
      - mssql
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=mssql+pyodbc://sa:123456789@mssql:1433/AnimalDetectionDB?driver=ODBC+Driver+17+for+SQL+Server
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:

volumes:
  mssql-data: